_target_: lambo.optimizers.eo_direct.ModelFreeGeneticOptimizer
_recursive_: False
num_rounds: 10000
num_gens: 2
seed: ${seed}
concentrate_pool: 1
residue_sampler: uniform
resampling_weight: 1.
simplex_bins: 20