_target_: lambo.optimizers.mogfn.MOGFN
_recursive_: False
num_rounds: 64
num_gens: 16
random_action_prob: 0.01
max_len: ${task.max_len}
batch_size: 32
reward_exp: 4
reward_min: 1e-80
reward_max: 100
sampling_temp: 1
train_steps: 100
temp_use_therm: True
pref_use_therm: True
pi_lr: 0.0001
z_lr: 0.001
wd: 0.0001
therm_n_bins: 50
gen_clip: 10
encoder_obj: mlm
sample_beta: 4

model:
  _target_: lambo.models.cond_gfn_transformer.CondGFNTransformer
  max_len: ${task.max_len}
  vocab_size: 26
  num_actions: 21
  num_hid: 64
  num_layers: 5
  num_head: 8
  bidirectional: False
  dropout: 0
  batch_size: 32